---
- name: Install dependencies.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker repo.
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install docker.
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - Restart docker daemon.
